name: fit_pro_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.1
  lottie: ^3.1.2
  logger: ^2.4.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.1.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  syncfusion_flutter_calendar: ^26.2.5
  syncfusion_localizations: ^26.2.5
  flutter_launcher_icons: ^0.13.1
  city_picker_from_map: ^0.0.1
  flutter_xlider: ^3.5.0
  fl_chart: ^0.68.0
  flutter_animate: ^4.5.0
  video_player: ^2.9.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  timer_count_down: ^2.2.2
  another_flushbar: ^1.12.30
  intl_phone_number_input: ^0.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/map_style.json
    - assets/videos/sample_video.mp4
    - assets/animations/circular_dot_animation.json
    - assets/animations/touch_app.json
    - assets/animations/loading_round.json


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"